name: Perform Checks
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        run: |
          rustup update stable && rustup default stable
          rustup component add rustfmt
          rustup component add clippy
      - name: Check Build
        run: cargo check
      - name: Check Format
        run: cargo fmt --all --check
      - name: Check Clippy
        run: cargo clippy --workspace --all-targets --no-deps -- -D warnings
